apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bmazlda0m-go-gitops
  description: This is GitOps manifest for bmazlda0m-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bmazlda0m-go
    backstage.io/kubernetes-id: bmazlda0m-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bmazlda0m-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bmazlda0m-go
